name: Process Videos with FFmpeg

on:
  # Manual trigger via API or web interface
  workflow_dispatch:
    inputs:
      video_id:
        description: 'Video ID to process'
        required: true
        type: string

jobs:
  process-video:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt
      
      - name: Install FFmpeg and yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          ffmpeg -version
          pip install yt-dlp
      
      - name: Process YouTube video
        env:
          VIDEO_ID: ${{ github.event.inputs.video_id }}
          R2_SHORTS_ACCESS_KEY: ${{ secrets.R2_SHORTS_ACCESS_KEY }}
          R2_SHORTS_SECRET_KEY: ${{ secrets.R2_SHORTS_SECRET_KEY }}
          R2_SHORTS_ENDPOINT: ${{ secrets.R2_SHORTS_ENDPOINT }}
          R2_SHORTS_BUCKET: ${{ secrets.R2_SHORTS_BUCKET }}
          R2_SHORTS_PUBLIC_URL: ${{ secrets.R2_SHORTS_PUBLIC_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python .github/scripts/process_youtube_video.py
      
      - name: Clean up
        if: always()
        run: |
          rm -rf temp/ downloads/ shorts/
          echo "Cleanup completed"
      
      - name: Summary
        run: |
          echo "✅ Video processing completed for: ${{ github.event.inputs.video_id }}"
          echo "Check the logs above for detailed information"
